server.port=8080

# Database settings
spring.datasource.url=jdbc:postgresql://main-db:5432/explore_with_me_main
spring.datasource.username=main_user
spring.datasource.password=main_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# SQL logging
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Actuator settings
management.endpoints.web.exposure.include=health,info,metrics

# Statistics service URL
stats-server.url=http://stats-service:9090