server.port=8080

# Database settings for Docker
spring.datasource.url=jdbc:postgresql://main-db:5432/explore_with_me_main
spring.datasource.username=main_user
spring.datasource.password=main_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Time
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

# Statistics service URL for Docker
stats-server.url=http://stats-service:9090